/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppAcademicRouteImport } from './routes/app.academic'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppInternshipsRouteImport } from './routes/app.internships'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppPlacementsRouteImport } from './routes/app.placements'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAcademicRoute = AppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppInternshipsRoute = AppInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementsRoute = AppPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/progress': typeof AppProgressRoute
  '/app/reviews': typeof AppReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/progress': typeof AppProgressRoute
  '/app/reviews': typeof AppReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/progress': typeof AppProgressRoute
  '/app/reviews': typeof AppReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/academic'
    | '/app/applications'
    | '/app/attendance'
    | '/app/internships'
    | '/app/onboarding'
    | '/app/placements'
    | '/app/progress'
    | '/app/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/academic'
    | '/app/applications'
    | '/app/attendance'
    | '/app/internships'
    | '/app/onboarding'
    | '/app/placements'
    | '/app/progress'
    | '/app/reviews'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/academic'
    | '/app/applications'
    | '/app/attendance'
    | '/app/internships'
    | '/app/onboarding'
    | '/app/placements'
    | '/app/progress'
    | '/app/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/academic': {
      id: '/app/academic'
      path: '/academic'
      fullPath: '/app/academic'
      preLoaderRoute: typeof AppAcademicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/internships': {
      id: '/app/internships'
      path: '/internships'
      fullPath: '/app/internships'
      preLoaderRoute: typeof AppInternshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/placements': {
      id: '/app/placements'
      path: '/placements'
      fullPath: '/app/placements'
      preLoaderRoute: typeof AppPlacementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicRoute: typeof AppAcademicRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppInternshipsRoute: typeof AppInternshipsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlacementsRoute: typeof AppPlacementsRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReviewsRoute: typeof AppReviewsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicRoute: AppAcademicRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppInternshipsRoute: AppInternshipsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlacementsRoute: AppPlacementsRoute,
  AppProgressRoute: AppProgressRoute,
  AppReviewsRoute: AppReviewsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
